// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer-service.proto

package com.fuchuan.customerservice.common;

public interface AccountBaseInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fuchuan.customerservice.common.AccountBaseInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string nickName = 3;</code>
   */
  java.lang.String getNickName();
  /**
   * <code>string nickName = 3;</code>
   */
  com.google.protobuf.ByteString
      getNickNameBytes();

  /**
   * <code>string avatar = 4;</code>
   */
  java.lang.String getAvatar();
  /**
   * <code>string avatar = 4;</code>
   */
  com.google.protobuf.ByteString
      getAvatarBytes();
}
