// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer-service.proto

package com.fuchuan.customerservice.common;

public interface AccountBaseInfoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fuchuan.customerservice.common.AccountBaseInfoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.com.fuchuan.customerservice.common.Code code = 1;</code>
   */
  int getCodeValue();
  /**
   * <code>.com.fuchuan.customerservice.common.Code code = 1;</code>
   */
  com.fuchuan.customerservice.common.Code getCode();

  /**
   * <code>.com.fuchuan.customerservice.common.AccountBaseInfo account = 2;</code>
   */
  boolean hasAccount();
  /**
   * <code>.com.fuchuan.customerservice.common.AccountBaseInfo account = 2;</code>
   */
  com.fuchuan.customerservice.common.AccountBaseInfo getAccount();
  /**
   * <code>.com.fuchuan.customerservice.common.AccountBaseInfo account = 2;</code>
   */
  com.fuchuan.customerservice.common.AccountBaseInfoOrBuilder getAccountOrBuilder();

  /**
   * <code>.com.fuchuan.customerservice.common.Role role = 3;</code>
   */
  int getRoleValue();
  /**
   * <code>.com.fuchuan.customerservice.common.Role role = 3;</code>
   */
  com.fuchuan.customerservice.common.Role getRole();
}
