// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer-service.proto

package com.fuchuan.customerservice.common;

public final class CustomerServiceGrpc {
  private CustomerServiceGrpc() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuchuan_customerservice_common_AccountBaseInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReply_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuchuan_customerservice_common_Waiters_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuchuan_customerservice_common_Waiters_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_fuchuan_customerservice_common_WaitersReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_fuchuan_customerservice_common_WaitersReq_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026customer-service.proto\022\"com.fuchuan.cu" +
      "stomerservice.common\"?\n\017AccountBaseInfo\022" +
      "\n\n\002id\030\002 \001(\t\022\020\n\010nickName\030\003 \001(\t\022\016\n\006avatar\030" +
      "\004 \001(\t\" \n\022AccountBaseInfoReq\022\n\n\002id\030\001 \001(\t\"" +
      "\314\001\n\024AccountBaseInfoReply\0226\n\004code\030\001 \001(\0162(" +
      ".com.fuchuan.customerservice.common.Code" +
      "\022D\n\007account\030\002 \001(\01323.com.fuchuan.customer" +
      "service.common.AccountBaseInfo\0226\n\004role\030\003" +
      " \001(\0162(.com.fuchuan.customerservice.commo" +
      "n.Role\")\n\033FetchAccountListBaseInfoReq\022\n\n" +
      "\002id\030\001 \003(\t\"e\n\035FetchAccountListBaseInfoRep" +
      "ly\022D\n\007account\030\001 \003(\01323.com.fuchuan.custom" +
      "erservice.common.AccountBaseInfo\"O\n\007Wait" +
      "ers\022D\n\007account\030\001 \003(\01323.com.fuchuan.custo" +
      "merservice.common.AccountBaseInfo\"\014\n\nWai" +
      "tersReq*\341\002\n\007Command\022\022\n\016COMMAND_UNKNOW\020\000\022" +
      "\031\n\025COMMAND_HANDSHAKE_REQ\020\001\022\032\n\026COMMAND_HA" +
      "NDSHAKE_RESP\020\002\022\024\n\020COMMAND_CHAT_REQ\020\t\022\031\n\025" +
      "COMMAND_HEARTBEAT_REQ\020\017\022\032\n\026COMMAND_HEART" +
      "BEAT_RESP\020\020\022\024\n\020COMMAND_CALL_REQ\020\030\022\025\n\021COM" +
      "MAND_CALL_RESP\020\031\022\027\n\023COMMAND_REMIND_PUSH\020" +
      "\032\022\027\n\023COMMAND_ONLINE_PUSH\020\034\022\030\n\024COMMAND_OF" +
      "FLINE_PUSH\020\035\022\034\n\030COMMAND_CLEAR_REMIND_REQ" +
      "\020\033\022\'\n#COMMAND_ONLINE_NOTIFY_SUBSCRIBE_RE" +
      "Q\020\036*!\n\004Code\022\006\n\002OK\020\000\022\021\n\004FAIL\020\377\377\377\377\377\377\377\377\377\001* " +
      "\n\004Role\022\014\n\010CUSTOMER\020\000\022\n\n\006WAITER\020\0012\242\003\n\016Acc" +
      "ountService\022\201\001\n\rFetchBaseInfo\0226.com.fuch" +
      "uan.customerservice.common.AccountBaseIn" +
      "foReq\0328.com.fuchuan.customerservice.comm" +
      "on.AccountBaseInfoReply\022\236\001\n\030FetchAccount" +
      "ListBaseInfo\022?.com.fuchuan.customerservi" +
      "ce.common.FetchAccountListBaseInfoReq\032A." +
      "com.fuchuan.customerservice.common.Fetch" +
      "AccountListBaseInfoReply\022k\n\014FetchWaiters" +
      "\022..com.fuchuan.customerservice.common.Wa" +
      "itersReq\032+.com.fuchuan.customerservice.c" +
      "ommon.WaitersB@\n\"com.fuchuan.customerser" +
      "vice.commonB\023CustomerServiceGrpcP\001\242\002\002CSb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuchuan_customerservice_common_AccountBaseInfo_descriptor,
        new java.lang.String[] { "Id", "NickName", "Avatar", });
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReply_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuchuan_customerservice_common_AccountBaseInfoReply_descriptor,
        new java.lang.String[] { "Code", "Account", "Role", });
    internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReply_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReply_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_fuchuan_customerservice_common_Waiters_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_fuchuan_customerservice_common_Waiters_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuchuan_customerservice_common_Waiters_descriptor,
        new java.lang.String[] { "Account", });
    internal_static_com_fuchuan_customerservice_common_WaitersReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_fuchuan_customerservice_common_WaitersReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_fuchuan_customerservice_common_WaitersReq_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
