// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer-service.proto

package com.fuchuan.customerservice.common;

/**
 * Protobuf type {@code com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq}
 */
public  final class FetchAccountListBaseInfoReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq)
    FetchAccountListBaseInfoReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FetchAccountListBaseInfoReq.newBuilder() to construct.
  private FetchAccountListBaseInfoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FetchAccountListBaseInfoReq() {
    id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FetchAccountListBaseInfoReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              id_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            id_.add(s);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        id_ = id_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.fuchuan.customerservice.common.CustomerServiceGrpc.internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.fuchuan.customerservice.common.CustomerServiceGrpc.internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq.class, com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList id_;
  /**
   * <code>repeated string id = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getIdList() {
    return id_;
  }
  /**
   * <code>repeated string id = 1;</code>
   */
  public int getIdCount() {
    return id_.size();
  }
  /**
   * <code>repeated string id = 1;</code>
   */
  public java.lang.String getId(int index) {
    return id_.get(index);
  }
  /**
   * <code>repeated string id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getIdBytes(int index) {
    return id_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < id_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < id_.size(); i++) {
        dataSize += computeStringSizeNoTag(id_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getIdList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq)) {
      return super.equals(obj);
    }
    com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq other = (com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq) obj;

    boolean result = true;
    result = result && getIdList()
        .equals(other.getIdList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getIdCount() > 0) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getIdList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq)
      com.fuchuan.customerservice.common.FetchAccountListBaseInfoReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.fuchuan.customerservice.common.CustomerServiceGrpc.internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.fuchuan.customerservice.common.CustomerServiceGrpc.internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq.class, com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq.Builder.class);
    }

    // Construct using com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.fuchuan.customerservice.common.CustomerServiceGrpc.internal_static_com_fuchuan_customerservice_common_FetchAccountListBaseInfoReq_descriptor;
    }

    @java.lang.Override
    public com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq getDefaultInstanceForType() {
      return com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq.getDefaultInstance();
    }

    @java.lang.Override
    public com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq build() {
      com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq buildPartial() {
      com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq result = new com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        id_ = id_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.id_ = id_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq) {
        return mergeFrom((com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq other) {
      if (other == com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq.getDefaultInstance()) return this;
      if (!other.id_.isEmpty()) {
        if (id_.isEmpty()) {
          id_ = other.id_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureIdIsMutable();
          id_.addAll(other.id_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureIdIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        id_ = new com.google.protobuf.LazyStringArrayList(id_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getIdList() {
      return id_.getUnmodifiableView();
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public int getIdCount() {
      return id_.size();
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public java.lang.String getId(int index) {
      return id_.get(index);
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes(int index) {
      return id_.getByteString(index);
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public Builder setId(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
      id_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public Builder addId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureIdIsMutable();
      id_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public Builder addAllId(
        java.lang.Iterable<java.lang.String> values) {
      ensureIdIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, id_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public Builder clearId() {
      id_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string id = 1;</code>
     */
    public Builder addIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureIdIsMutable();
      id_.add(value);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq)
  }

  // @@protoc_insertion_point(class_scope:com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq)
  private static final com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq();
  }

  public static com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FetchAccountListBaseInfoReq>
      PARSER = new com.google.protobuf.AbstractParser<FetchAccountListBaseInfoReq>() {
    @java.lang.Override
    public FetchAccountListBaseInfoReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FetchAccountListBaseInfoReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FetchAccountListBaseInfoReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FetchAccountListBaseInfoReq> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.fuchuan.customerservice.common.FetchAccountListBaseInfoReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

