// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer-service.proto

package com.fuchuan.customerservice.common;

public interface FetchAccountListBaseInfoReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fuchuan.customerservice.common.FetchAccountListBaseInfoReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.fuchuan.customerservice.common.AccountBaseInfo account = 1;</code>
   */
  java.util.List<com.fuchuan.customerservice.common.AccountBaseInfo> 
      getAccountList();
  /**
   * <code>repeated .com.fuchuan.customerservice.common.AccountBaseInfo account = 1;</code>
   */
  com.fuchuan.customerservice.common.AccountBaseInfo getAccount(int index);
  /**
   * <code>repeated .com.fuchuan.customerservice.common.AccountBaseInfo account = 1;</code>
   */
  int getAccountCount();
  /**
   * <code>repeated .com.fuchuan.customerservice.common.AccountBaseInfo account = 1;</code>
   */
  java.util.List<? extends com.fuchuan.customerservice.common.AccountBaseInfoOrBuilder> 
      getAccountOrBuilderList();
  /**
   * <code>repeated .com.fuchuan.customerservice.common.AccountBaseInfo account = 1;</code>
   */
  com.fuchuan.customerservice.common.AccountBaseInfoOrBuilder getAccountOrBuilder(
      int index);
}
