// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: customer-service.proto

package com.fuchuan.customerservice.common;

public interface WaitersReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.fuchuan.customerservice.common.WaitersReq)
    com.google.protobuf.MessageOrBuilder {
}
